// Chinese homepage copy keyed by the English source text used in the shared template.
export default {
  "Fire protection equipment": "消防设备制造与供应",
  "Products": "产品",
  "About": "关于我们",
  "Manufacturing": "制造能力",
  "Downloads": "资料下载",
  "Contact": "联系",
  "Manufacturer · Fire-water system components": "制造商 · 消防给水系统组件",
  "Fire Protection Equipment Manufacturing & OEM Support.": "消防设备制造与OEM配套支持",
  "Sprinklers, alarm and control valves, hose reels, fire hoses, nozzles, couplings and hydrant-system components for trading partners, distributors and private-label customers.": "面向贸易合作伙伴、经销商和自有品牌客户，提供消防喷头、报警与控制阀、软管卷盘、消防水带、水枪、接口及消火栓系统组件。",
  "Explore Products": "查看产品",
  "Contact Manufacturing Team": "联系制造团队",
  "Company established": "公司成立",
  "Production space stated by company": "公司提供的生产车间面积",
  "Machining capability": "机加工能力",
  "Machining & production": "机加工与生产",
  "About the manufacturer": "关于制造商",
  "Manufacturing support built around real product requirements.": "围绕真实产品要求提供制造支持",
  "Based in Nan'an, Quanzhou, Fujian, we manufacture and supply fire-water-system products and components. We work with trading partners and private-label customers, supporting product configuration, marking, packaging and production review.": "我们位于福建泉州南安，生产和供应消防给水系统产品及组件，并为贸易合作伙伴和自有品牌客户提供产品配置、标识、包装和生产评审支持。",
  "International thread, flange or grooved requirements are reviewed against the buyer's drawing, sample and technical schedule before confirmation. CNC capability alone is not presented as proof of compliance with a specific overseas standard.": "国际螺纹、法兰或沟槽要求需根据买方图纸、样品和技术清单进行评审后确认。CNC加工能力本身不作为符合某项海外标准的证明。",
  "Product configuration review": "产品配置评审",
  "By model and target requirement": "按型号和目标要求确认",
  "Domestic inspection documentation": "国内检测资料",
  "Scope confirmed before supply": "供货前确认适用范围",
  "Private-label support": "自有品牌支持",
  "Marking and packaging review": "标识和包装评审",
  "Mixed product sourcing": "多产品配套",
  "Fire-water-system components": "消防给水系统组件",
  "Product range": "产品范围",
  "Select by product family, size and project requirement.": "按产品系列、尺寸和项目要求选型",
  "International descriptions are used first; factory reference codes remain available for quotation and production coordination.": "优先使用国际通用产品名称；工厂参考型号保留用于报价和生产对应。",
  "Fire Sprinklers": "消防喷头",
  "Upright, pendent, sidewall, concealed and special-purpose configurations.": "上喷、下喷、边墙、隐蔽式及特殊用途系列。",
  "View range →": "查看系列 →",
  "Alarm & System Valves": "报警阀与系统阀门",
  "Wet alarm, deluge, preaction and dry-pipe valve families.": "湿式、雨淋、预作用和干式阀组系列。",
  "Fire Butterfly Valves": "消防蝶阀",
  "Lever-operated and supervisory configurations with wafer or grooved connections.": "手柄式和信号监控型，可选对夹或沟槽连接。",
  "Fire Gate Valves": "消防闸阀",
  "Supervisory, NRS and OS&Y configurations in grooved or flanged styles.": "信号、暗杆及明杆结构，提供沟槽式或法兰式。",
  "Fire Hose Reels": "消防软管卷盘",
  "RIA 25 European-standard (EN 671-1) and JPS direct-stream and jet/spray reel configurations.": "欧标RIA25及JPS直流/喷雾卷盘配置。",
  "Hoses, Nozzles & Couplings": "消防水带、水枪与接口",
  "Components or matched hose-line assemblies for quotation.": "可按单品或完整水带线路总成询价。",
  "Indoor Fire Hydrants": "室内消火栓",
  "Indoor fire-water outlets and matching system components.": "室内消防给水出口及配套组件。",
  "View product →": "查看产品 →",
  "Outdoor Fire Hydrants": "室外消火栓",
  "Above-ground hydrant configurations for fire-water networks.": "用于消防给水管网的地上式消火栓配置。",
  "Fire Department Connections": "消防水泵接合器",
  "Inlet assemblies connecting fire-service water supply to building systems.": "连接消防车供水与建筑消防系统的进水组件。",
  "Manufacturing overview": "制造能力概览",
  "Production, machining and organized order preparation.": "生产、机加工与订单备货",
  "The visuals below provide an overview of manufacturing, product handling and order preparation. Technical compliance remains model- and document-specific.": "以下画面用于概览制造、产品处理和订单备货能力。技术符合性仍需按具体型号和文件确认。",
  "Machining": "机加工",
  "CNC and workshop processes support component production and configuration review.": "CNC和车间工序支持组件生产及配置评审。",
  "Batch Production": "批量生产",
  "Organized production of hydrants, valves and fire-water-system components.": "消火栓、阀门和消防给水系统组件的有序生产。",
  "Order Preparation": "订单备货",
  "Structured storage supports product sorting, packing and shipment coordination.": "有序仓储支持产品分拣、包装和发运协调。",
  "Manufacturing Base": "制造基地",
  "Fire-protection equipment production in Nan'an, Quanzhou, Fujian, China.": "位于中国福建泉州南安的消防设备生产基地。",
  "Configuration first. Production after confirmation.": "先确认配置，再安排生产",
  "We can review product marking, nameplates, carton artwork, selected finishes and component combinations. Thread, flange and grooved requirements are confirmed from drawings, samples or technical schedules—not assumed from machine capability.": "可评审产品标识、铭牌、纸箱设计、部分表面处理和组件组合。螺纹、法兰和沟槽要求需根据图纸、样品或技术清单确认，不根据设备能力直接推定。",
  "Product marking & nameplate": "产品标识与铭牌",
  "Carton artwork & labels": "纸箱设计与标签",
  "Component matching": "组件配套",
  "Drawing / sample review": "图纸 / 样品评审",
  "Discuss Your Requirement": "沟通订制需求",
  "Kraft carton — illustrative option": "牛皮纸箱—包装形式示意",
  "Custom carton — illustrative option": "彩箱—包装形式示意",
  "Wooden case — illustrative option": "木箱—包装形式示意",
  "Packaging visuals show possible formats only. Final packaging is confirmed by product, order and transport requirement.": "包装图片仅展示可能的形式。最终包装按产品、订单和运输要求确认。",
  "Verified management systems": "已核实管理体系",
  "Certificate details shown with holder and scope.": "展示证书持有人与覆盖范围",
  "These are management-system certificates, not UL, FM, CE or overseas product approvals. Product-specific domestic reports and certificate applicability are confirmed separately.": "以下为管理体系证书，并非UL、FM、CE或海外产品认证。具体产品的国内检测报告和适用范围需另行确认。",
  "Certificate holder shown on the documents: GUANYA FIRE-PROTECTION EQUIPMENT CO., LTD. Scope shown on the documents covers production of fire hydrants, sprinkler tips, fire hose reels and fire pump adapters, plus sales of fire hose.": "证书所示持有人：GUANYA FIRE-PROTECTION EQUIPMENT CO., LTD（冠亚消防器材有限公司）。证书范围包括消火栓、消防喷头、消防软管卷盘、消防水泵接合器的生产及消防水带销售。",
  "Certificate no.": "证书编号",
  "Recertification": "再认证日期",
  "Expiry": "有效期至",
  "Quality management system. Click to view the supplied certificate.": "质量管理体系。点击查看所提供证书。",
  "Initial issuance": "初次发证",
  "Environmental management system. Click to view the supplied certificate.": "环境管理体系。点击查看所提供证书。",
  "Occupational health and safety management system. Click to view the supplied certificate.": "职业健康安全管理体系。点击查看所提供证书。",
  "Technical & commercial inquiry": "技术与商务询盘",
  "Send the product, size and target requirement.": "发送产品、尺寸和目标要求",
  "For a useful review, include product family, quantity, destination, required connection or drawing, packaging request and any approval requirement.": "为便于有效评审，请提供产品系列、数量、目的地、所需连接或图纸、包装要求及认证要求。",
  "Nan'an, Quanzhou, Fujian, China": "中国福建省泉州市南安市",
  "Name / company": "姓名 / 公司",
  "Destination": "目的地",
  "Product family": "产品系列",
  "Estimated quantity": "预计数量",
  "Size / connection / drawing / OEM requirement": "尺寸 / 连接 / 图纸 / OEM要求",
  "Continue on WhatsApp ↗": "通过WhatsApp继续 ↗",
  "Fire protection equipment manufacturing and supply": "消防设备制造与供应",
  "Website information is for product-range reference. Final specifications, connection standards, test documentation and certificate applicability are confirmed by model and order before supply.": "网站信息用于产品范围参考。最终规格、连接标准、检测资料和证书适用性在供货前按型号和订单确认。"
};
