import { SITE_ORIGIN, SUPPORTED_LOCALES, createListingPageRoute, resolveSiteRoute } from "./siteRoutes.js";
import { createSeoMetadata } from "./seo.js";
import { createSiteNavigation } from "./navigation.js";

const common = {
  en: { lang: "en", dir: "ltr", locale: "en_US", alternateLocale: "ar_AR", brandTagline: "Fire protection equipment manufacturing and supply", nav: { home: "Home", products: "Products", about: "About", downloads: "Catalog & Files", contact: "Contact" }, languages: { en: "English", ar: "العربية" }, skip: "Skip to content", menu: "Open menu", productOptions: [["Fire Sprinklers", "Fire Sprinklers"], ["Alarm & System Valves", "Alarm & System Valves"], ["Fire Butterfly / Gate Valves", "Fire Butterfly / Gate Valves"], ["Fire Hose Reels", "Fire Hose Reels"], ["Hoses, Nozzles & Couplings", "Hoses, Nozzles & Couplings"], ["Hydrants & Connections", "Hydrants & Connections"], ["Other", "Other"]], footerSummary: "Manufacturing and supply of fire-water-system components with private-label project support.", footerDisclaimer: "Website information indicates product scope. Final specifications, connection standards, test documents and certificate applicability are confirmed by model and order before supply." },
  ar: { lang: "ar", dir: "rtl", locale: "ar_AR", alternateLocale: "en_US", brandTagline: "تصنيع وتوريد معدات مكافحة الحريق", nav: { home: "الرئيسية", products: "المنتجات", about: "عن الشركة", downloads: "الكتالوج والملفات", contact: "تواصل معنا" }, languages: { en: "English", ar: "العربية" }, skip: "انتقل إلى المحتوى", menu: "فتح القائمة", productOptions: [["Fire Sprinklers", "رشاشات الحريق"], ["Alarm & System Valves", "صمامات الإنذار وصمامات الأنظمة"], ["Fire Butterfly / Gate Valves", "صمامات الفراشة والبوابة"], ["Fire Hose Reels", "بكرات خراطيم الحريق"], ["Hoses, Nozzles & Couplings", "الخراطيم والفوهات والوصلات"], ["Hydrants & Connections", "صنابير الحريق والوصلات"], ["Other", "أخرى"]], footerSummary: "تصنيع وتوريد مكونات أنظمة مياه مكافحة الحريق ودعم مشاريع العلامة الخاصة.", footerDisclaimer: "معلومات الموقع مرجع لنطاق المنتجات. تُؤكد المواصفات النهائية ومعايير التوصيل ووثائق الاختبار وانطباق الشهادات حسب الموديل والطلب قبل التوريد." }
};

const pages = {
  about: {
    en: { title: "About the Manufacturer | CHUANWEI FIRE", description: "Learn about CHUANWEI FIRE manufacturing and supply support for fire-water-system components, OEM review and private-label projects in Nan'an, Quanzhou, China.", eyebrow: "CHUANWEI FIRE", heroTitle: "A manufacturing source for fire-water-system components", heroLead: "We support trading partners, distributors and private-label customers by reviewing product configuration, marking and packaging before production.", introTitle: "Production follows the confirmed model and requirement.", intro: ["Based in Nan'an, Quanzhou, Fujian, China, we manufacture and supply fire-water-system products and components and coordinate configuration, marking and packaging with international buyers.", "Company-provided information states establishment in 2017 and 5,000 m² of production space. CNC capability supports component machining; it is not presented as proof of compliance with any specific standard or approval."], features: [["Product review", "By product family, model and destination market"], ["Production coordination", "After technical and commercial requirements are fixed"], ["Private label", "Review of marking, nameplate and packaging"], ["Drawing and sample support", "For requested connections and dimensions"]], capabilitiesTitle: "From technical review to order preparation.", capabilitiesLead: "Final project details are determined by the agreed model, document, sample or drawing.", capabilities: [["Component machining", "CNC and workshop processes support production of agreed product components."], ["Batch production", "Organized production of hydrants, valves and fire-water-system components."], ["Storage and packing", "Product sorting, packing and shipment coordination according to order and transport requirements."]], oemTitle: "Confirm the configuration first, then arrange production.", oemBody: "We can review product marking, nameplates, carton artwork, selected finishes and component combinations. Thread, flange and grooved-end requirements are reviewed against a drawing, sample or technical schedule.", oemItems: [["Marking and nameplate", "Using customer-confirmed content"], ["Packaging artwork and labels", "Reviewed by product and order"], ["Accessory combinations", "According to the agreed configuration list"], ["Colors and finishes", "Feasibility confirmed for each product"]], certificateNote: "The documents displayed on this site are management-system certificates. They are not, by themselves, UL, FM, CE or other product approvals. Test documents and certificate applicability are reviewed separately for each product.", downloadCta: "View available certificates and file options" },
    ar: { title: "عن الشركة | CHUANWEI FIRE", description: "تعرف على CHUANWEI FIRE وإمكانات تصنيع وتوريد مكونات أنظمة مياه مكافحة الحريق ودعم OEM والعلامة الخاصة في نانآن، تشيوانتشو، الصين.", eyebrow: "CHUANWEI FIRE", heroTitle: "جهة تصنيع لمكونات أنظمة مياه مكافحة الحريق", heroLead: "نخدم الشركاء التجاريين والموزعين وعملاء العلامة الخاصة من خلال مراجعة المنتج والتكوين والوسم والتعبئة قبل الإنتاج.", introTitle: "الإنتاج مرتبط بالموديل والمتطلبات المؤكدة.", intro: ["تقع عملياتنا في نانآن، تشيوانتشو، فوجيان، الصين. نصنّع ونورّد منتجات ومكونات أنظمة مياه مكافحة الحريق، وننسق مع المشترين الدوليين حول التكوين والوسم والتعبئة.", "تذكر بيانات الشركة أنها تأسست في 2017 وأن مساحة الإنتاج تبلغ 5,000 m². تدعم إمكانات CNC تشغيل المكونات، لكنها لا تُعد دليلاً على المطابقة لمعيار أو اعتماد محدد."], features: [["مراجعة المنتج", "حسب فئة المنتج والموديل والسوق المستهدف"], ["تنسيق الإنتاج", "بعد تثبيت المتطلبات الفنية والتجارية"], ["العلامة الخاصة", "مراجعة الوسم ولوحة البيانات والعبوة"], ["دعم الرسومات والعينات", "لمراجعة التوصيلات والأبعاد المطلوبة"]], capabilitiesTitle: "من المراجعة الفنية إلى تجهيز الطلب.", capabilitiesLead: "تُحدد التفاصيل النهائية لكل مشروع من خلال الموديل والوثيقة والعينة أو الرسم المتفق عليه.", capabilities: [["تشغيل المكونات", "عمليات الورشة وتشغيل CNC لدعم إنتاج مكونات المنتجات المتفق عليها."], ["الإنتاج المجمع", "تنظيم إنتاج صنابير الحريق والصمامات ومكونات شبكات مياه الحريق."], ["التخزين والتعبئة", "فرز المنتجات وتجهيز العبوات وتنسيق الشحن حسب الطلب ومتطلبات النقل."]], oemTitle: "تأكيد التكوين أولاً، ثم ترتيب الإنتاج.", oemBody: "يمكننا مراجعة وسم المنتج ولوحات البيانات وتصميم الكرتون وبعض خيارات التشطيب وتركيبات المكونات. تُراجع متطلبات اللولب والفلنجات والنهايات المحززة من الرسم أو العينة أو الجدول الفني.", oemItems: [["الوسم ولوحة البيانات", "وفق المحتوى الذي يؤكده العميل"], ["تصميم العبوة والملصق", "يُراجع حسب المنتج والطلب"], ["تركيب الملحقات", "حسب قائمة التكوين المتفق عليها"], ["الألوان والتشطيبات", "تُؤكد إمكانيتها لكل منتج"]], certificateNote: "الوثائق المعروضة في الموقع تخص أنظمة الإدارة، وليست بحد ذاتها اعتمادات منتجات مثل UL أو FM أو CE. تُراجع وثائق الاختبار وانطباق الشهادة لكل منتج على حدة.", downloadCta: "عرض الشهادات وخيارات الملفات المتاحة" }
  },
  downloads: {
    en: { title: "Catalog & Files | CHUANWEI FIRE", description: "Request the current CHUANWEI FIRE catalog and view the available management-system certificates. Technical files are supplied by model after product scope is confirmed.", eyebrow: "Catalog and files", heroTitle: "Available catalog and documents", heroLead: "Request the latest material for the product family you need. Data sheets and technical documents are provided by model after the request scope is confirmed.", resources: [["Current product catalog", "Tell us which product families you need so the sales team can provide the relevant current version.", "catalog"], ["Technical data sheets", "Provided by requested model, size and connection. No general file is represented as applying automatically to every product.", "contact"], ["Drawings and samples", "A customer drawing or sample can be reviewed for flange, grooved-end, thread or assembly configuration.", "contact"]], catalogAction: "Request the current catalog", contactAction: "Send the model, image or drawing", certificatesEyebrow: "Management systems", certificatesTitle: "Certificates shown with their correct scope.", certificatesLead: "These are management-system certificates, not UL, FM, CE or other product approvals. Applicability to a specific product is reviewed separately.", holderNote: "Certificate holder shown on the documents: GUANYA FIRE-PROTECTION EQUIPMENT CO., LTD. The files below are the public certificate materials currently available on this site.", viewFile: "Open certificate file", finalNote: "If your project requires a specific test report, certificate or connection standard, send the document name and destination market. The team will confirm availability and applicability before making a commitment." },
    ar: { title: "الكتالوج والملفات | CHUANWEI FIRE", description: "مدخل طلب كتالوج CHUANWEI FIRE وعرض شهادات أنظمة الإدارة المتاحة. تُقدم الملفات الفنية حسب الموديل بعد تأكيد نطاق المنتج.", eyebrow: "الكتالوج والملفات", heroTitle: "الكتالوج والوثائق المتاحة", heroLead: "اطلب أحدث نسخة مرتبطة بفئة المنتج التي تهمك. تُرسل أوراق البيانات والوثائق الفنية بحسب الموديل بعد تأكيد نطاق الطلب.", resources: [["كتالوج المنتجات الحالي", "أخبرنا بالفئات المطلوبة حتى يرسل فريق المبيعات النسخة المناسبة ويؤكد مدى حداثتها.", "catalog"], ["أوراق البيانات الفنية", "تُقدم حسب الموديل والمقاس والتوصيل المطلوب. لا نعرض ملفاً عاماً على أنه ينطبق تلقائياً على جميع المنتجات.", "contact"], ["الرسومات والعينات", "يمكن مراجعة رسم أو عينة العميل لتأكيد الفلنجة أو الطرف المحزّز أو اللولب أو تكوين مجموعة المنتج.", "contact"]], catalogAction: "اطلب الكتالوج الحالي", contactAction: "أرسل الموديل أو الصورة أو الرسم", certificatesEyebrow: "أنظمة الإدارة", certificatesTitle: "الشهادات المعروضة مع نطاقها الصحيح.", certificatesLead: "هذه شهادات أنظمة إدارة، وليست اعتمادات منتج من UL أو FM أو CE. تُراجع قابلية تطبيق أي وثيقة على منتج محدد بصورة منفصلة.", holderNote: "حامل الشهادات الظاهر في الوثائق: GUANYA FIRE-PROTECTION EQUIPMENT CO., LTD. الملفات أدناه هي مواد الشهادات العامة المتاحة حالياً على هذا الموقع.", viewFile: "فتح ملف الشهادة", finalNote: "إذا كان مشروعك يحتاج تقرير اختبار أو شهادة أو معيار اتصال محدداً، أرسل اسم الوثيقة والسوق المستهدف. سيؤكد الفريق مدى التوفر والانطباق قبل تقديم أي التزام." }
  },
  contact: {
    en: { title: "Contact & Inquiry | CHUANWEI FIRE", description: "Send CHUANWEI FIRE an inquiry for fire sprinklers, valves, hose reels, hydrants and other fire-water-system components.", eyebrow: "Contact", heroTitle: "Send your product or project requirement", heroLead: "Clear product and project information helps us review the configuration and requested documents accurately.", inquiryEyebrow: "Technical and commercial inquiry", inquiryTitle: "Send the size, connection, quantity and destination.", inquiryBody: "You can add a product photo, drawing or reference model when starting the WhatsApp conversation. The team will confirm what is available before preparing an offer.", location: "Nan'an, Quanzhou, Fujian, China", form: { name: "Name / company", destination: "Destination country or port", product: "Product family", quantity: "Estimated quantity", details: "Size / connection / drawing / OEM requirement", quantityPlaceholder: "e.g. 500 pcs", detailsPlaceholder: "Tell us what needs to be confirmed...", submit: "Continue on WhatsApp" }, checklistEyebrow: "Quick checklist", checklistTitle: "Details that help speed up review.", checklistLead: "Not every detail is required for the first inquiry, but final specifications are not fixed until confirmed.", checklist: [["Product identification", "Family, product photo, reference model and nominal size in DN / inch."], ["Project requirements", "Connection type, drawing or sample, destination country and documents required for review."], ["Commercial requirements", "Estimated quantity, packaging, marking or nameplate and target order timing."]] },
    ar: { title: "تواصل واستفسار | CHUANWEI FIRE", description: "أرسل استفساراً إلى CHUANWEI FIRE عن رشاشات الحريق والصمامات وبكرات الخراطيم وصنابير الحريق ومكونات أنظمة مياه الحريق.", eyebrow: "تواصل معنا", heroTitle: "أرسل متطلبات المنتج أو المشروع", heroLead: "كلما كانت المعلومات أوضح، أمكن مراجعة المنتج والتكوين والوثائق المطلوبة بصورة أدق.", inquiryEyebrow: "استفسار فني وتجاري", inquiryTitle: "أرسل المقاس والوصلة والكمية والوجهة.", inquiryBody: "يمكنك إضافة صورة أو رسم أو رقم موديل عند بدء المحادثة على WhatsApp. سيؤكد الفريق ما هو متاح قبل إعداد العرض.", location: "نانآن، تشيوانتشو، فوجيان، الصين", form: { name: "الاسم / الشركة", destination: "بلد أو ميناء الوصول", product: "فئة المنتج", quantity: "الكمية التقديرية", details: "المقاس / التوصيل / الرسم / متطلبات OEM", quantityPlaceholder: "مثال: 500 قطعة", detailsPlaceholder: "اكتب المعلومات التي تحتاج إلى تأكيدها...", submit: "المتابعة عبر WhatsApp" }, checklistEyebrow: "قائمة تحقق سريعة", checklistTitle: "بيانات تساعد على تسريع المراجعة.", checklistLead: "لا يلزم أن تتوفر كل البيانات عند الاستفسار الأول، لكن لا تُثبت المواصفات النهائية قبل تأكيدها.", checklist: [["تعريف المنتج", "الفئة، صورة المنتج، الموديل المرجعي، والمقاس الاسمي DN / inch."], ["متطلبات المشروع", "نوع التوصيل، الرسم أو العينة، بلد الوجهة، وأي وثائق مطلوبة للمراجعة."], ["المتطلبات التجارية", "الكمية التقديرية، التغليف، الوسم أو لوحة البيانات، وموعد الطلب المستهدف."]] }
  }
};

const certificates = [
  { standard: "ISO 9001:2015", number: "43225Q0932R1S", file: "assets/home/certificates/iso-9001.png", en: "Quality management system", ar: "نظام إدارة الجودة" },
  { standard: "ISO 14001:2015", number: "43225E0623R0S", file: "assets/home/certificates/iso-14001.png", en: "Environmental management system", ar: "نظام الإدارة البيئية" },
  { standard: "ISO 45001:2018", number: "43225S0547R0S", file: "assets/home/certificates/iso-45001.png", en: "Occupational health and safety management system", ar: "نظام إدارة الصحة والسلامة المهنية" }
];

export default Object.keys(pages).flatMap((routeId) => SUPPORTED_LOCALES.map((locale) => {
  const route = createListingPageRoute(routeId, locale);
  const copy = { ...common[locale], ...pages[routeId][locale] };
  const ogImage = `${SITE_ORIGIN}/og-image.jpg`;
  return { routeId, pageType: routeId, route, navigation: createSiteNavigation(routeId, locale, route.outputPath), copy, ogImage, seo: createSeoMetadata(routeId, locale, { title: copy.title, description: copy.description, image: ogImage }), certificates: routeId === "downloads" ? certificates.map((certificate) => ({ ...certificate, description: certificate[locale], href: `${route.assetPrefix}${certificate.file}` })) : [], whatsapp: "https://wa.me/8617326528368", email: "zhengcolin1@gmail.com" };
}));
